package com.mthivakkar.milfordtrail;

public class speech_Content {

    public String stop1Text = "Welcome to the audio guided tour of the accessible Walking Trail located within the Milford Upper Charles Trail.  You are now in the Gazebo at the Milford Upper Charles Trail.  This audio guided tour is one and one-quarter miles in length.  The audio tour will guide you from the Gazebo to the first accessible bench located in a wonderfully quiet area. The trail provides a nature experience for bicyclists, children, fitness, and more.  Milford was the first town to open its section of the Upper Charles Trail.  The trail extends from the Milford town center north to the Hopkinton town line, east to the town of Holliston, and south to the Milford Senior Center. Members of the Milford Accessible Walking Trail Committee volunteered their time and expertise to develop this first of its kind Accessible Walking Trail.  The Accessible Walking Trail Committee and the Town of Milford gratefully thank the Friends of the Milford Upper Charles Trail for providing all of the financial resources for this accessible walking trail. The gazebo at Louisa Lake in which you are standing is a favorite town meeting place and is located at about the midpoint of the Milford trail. Now, please exit the gazebo, trail approximately 15 feet along the pathway, and stop when you reach the tactile plate. The audio tour will then continue.";

    public String stop2Text = "Please Stop. In front of you is Louisa Lake.  If the water is flowing, you may hear the water of Louisa Lake spilling over the five-foot high dam then under Dilla Street on its way to Milford Pond.  Louisa Lake covers approximately 18 acres. James Macuen created Louisa Lake in 1875.  After constructing the dam on the Upper Charles River, James Macuen used the water from the new Louisa Lake to own and operate the finest natural water ice house in New England. Louisa Lake was originally named after his youngest daughter but many people remember part of the Louisa Lake as being called Parker’s Pond.  The pond was a good source of ice for many years.  Unfortunately, the icehouse collapsed during a heavy rainstorm in July of 1938. Louisa Lake is a warm water fishery.  The species found in Louisa Lake that naturally reproduce are the Brown Bullhead, Bluegill, Pumpkin Seed, Yellow Perch, Large Mouth Bass, and Chain Pickerel.  Trout, which is a cold-water fish, are stocked in Louisa Lake by the Milford Conservation Commission and the Massachusetts Division of Fisheries & Wildlife every spring when the water is cold. Each year, Jerry’s Bait and Tackle and the local radio station, WMRC, sponsor the annual fishing derby at Louisa Lake. Now, please turn right and trail the grass line on your right for approximately 50 feet.  You may feel the path gently curve to the right.  Stop at the tactile plate. The audio tour will then continue.";


    public String stop3Text = "Please Stop. On your right is a grassy area with large pieces of Milford Granite arranged in a Stonehenge type arrangement.  If it is a nice day, there are likely people sitting on these large stones or children climbing on them. These granite rocks are filled with texture:  they have sharp edges from cutting tools and bristly lichen.  Lichen is live vegetation that grows on rocks.  It is part algae and part mushroom.  The more lichen the better because lack of lichen is evidence of air pollution.  It also suffocates in the sun and enjoys the dark, north face.  So, if you feel much lichen, you are feeling and looking at the north face. Now, please trail the tactile pavement on the right.  You are passing an entrance to the parking lot on your right.  Re-connect with the grass line on the right.  Continue to trail for 50 feet.  Stop at the tactile at the next tactile plate. The audio tour will then continue.";



    public String stop4Text = "Please Stop. At this location, you may smell the five large white pine trees nearby.  Usually white pines grow high and straight, but these white pines are full and wide.  Historically, white pines were cut for colonial ships’ masts. White pine needles are five needles to a bundle and the needles are very soft.  If you are able to pick up the needles, please feel the soft needles, five to a bundle.  Later in this audio presentation, we will point out that red pines have only two to a bundle.  White pines produce many more pine cones!  If you get off the trail, you will feel many of them lying around on the ground.  The squirrels and the birds will eat the pine nuts inside and abandon the cones.  That is why you can feel so many pinecones just lying around – the nuts have been consumed. In earlier times, the Kiwanis Club created a path where folks enjoyed picnicking and swimming.  Lights were set up for evening hockey games and campfires.  Between the parking lot and trail there is a red Cedar Street.  To your right, there are red pines in abundance.  They have two needles to a bundle, which are different from the white pines with five needles. Right away, you might sense the autumn olive – a deliciously fragrant bush.  Each flower has a berry, and the berries are editable.  The tastes like sweet tarts.  It was planted by the conservation corps decades ago to reduce erosion and to give wildlife food.  It worked very well, but too well, and is now considered invasive.  The bush is native to the Mediterranean. As you walk, please know that the autumn olive is everywhere.  The birds are everywhere.  Can you hear the blue jays?  The cat tails in the wetlands abutting the lake welcome red-winged blackbirds too. Now, please continue trailing along the right for 50 feet. The audio tour will then continue.";


    public String stop5Text = "Please Stop. Most of the Milford Upper Charles Trail corridor was originally a train track dating back to the 1880s.  It brought passengers and freight to the local area.  The old Hopkinton Railroad was constructed to connect the Milford & Woonsocket Railroad to the Boston & Albany Railroad in Ashland. The trains, with their cargo consisting of shoes and Milford’s famous pink granite, left the depot on Central Street destined to Boston.  Thus, the area became a thriving industrial center of Irish, Italian, Swedish, and other immigrants seeking work in the quarries and factories. In addition, low to the ground is the prickly multi-flora rose.  This plant was cultivated for ground cover to reduce erosion, but is invasive and can crawl over existing plants and reach heights of eight to ten feet.  Bittersweet, purple loosestrife, and Japanese knotweed are also invasive and found along the trail.  Low bush blueberries are native ground cover and along the trail. If you pause for a moment in this area, you will hear the song of different birds.  You may feel the soft flutter of a butterfly on your cheek because on nearby on your right is a butterfly garden planted by the Girl Sours.  Each year new scouts tend to the garden to keep it fresh.  The garden is maintained by Girl Scout Troup 11523 and consists of day lilies and some annuals such as begonias. Alder trees and their cone-like seeds attract chickadee birds.  Listen for the chickadee call – ti-ti-ti. Now, please continue to trail on your right until you locate the accessible bench.  You will know you have located the accessible bench when the grass line ends and the pavement pad on which the accessible bench is located. The audio tour will then continue.";


    public String stop6Text = "Please Stop. As you sit on this bench facing the Louisa Lake, there may be swans gliding past and there may be people fishing on the grassy slope that meets the water.  You may hear many birdsongs.  You may even be in the company of people lounging on the grassy slope looking out into the water.  Across the lake, you may hear cars and trucks on busy Purchase Street, which runs north and south. The first half of the audio tour is now completed. From this accessible bench, you will return to the Gazebo. To return to the Gazebo, now please cross the bike path that is directly in front of you.  Turn left.  Trail the grass line on your right. The audio tour will then continue.";

    public String stop7Text = "Please Stop. There is an abundance of staghorn sumac, which grows very tall with red berry crowns.  The stems are very soft like stags’ horns; hence the name.  Some grow very large, as large as trees.  Low to the ground are many plants called common mullein.  It is a biennial plant – it only blooms every other year.  However, every year, moths and caterpillars enjoy chewing at its leaves.  Other native plants are wild mustard and sweet gale. Now, please continue trailing on your right until you locate the next tactile plate.  This tactile plate is about 100 feet forward.  As you trail, you will feel the trail make a curve to the right. The audio tour will then continue.";


    public String stop8Text = "Please Stop. On your right is the Town of Milford’s accessible fishing pier.  This accessible fishing pier was constructed 2013 by the Milford Commission on Disabilities for the benefit of all persons with disabilities. Also, on your right is a grassy area that lies between the bike path and Louisa Lake.  There are several picnic tables, including one picnic table for persons who use wheelchairs.  Milfordians and visitors frequently gather at the picnic for picnic lunches. This picnic area is filled with sunshine. Now, please continue to trail along the right.  At the end of the tactile plate, reconnect with the grass line.  Trail on the right until you locate a granite block, which is about 50 feet forward.  As you trail, you will feel the trail make a curve to the left. When you reach the granite block, the audio tour will then continue.";

    public String stop9Text = "The dam is now on your right, Dilla Street is in front of you and the Gazebo is on your left. Now, please make a quarter turn to your left and cross the bike path.  Locate the narrow path to the gazebo and walk into the gazebo. The audio tour will then continue.";

    public String stop10Text = "This concludes the audio guided tour of the accessible Walking Trail located within the Milford Upper Charles Trail. The Milford Accessible Walking Trail Committee and The Friends of the Upper Charles Trail hope that you enjoyed this tour.";


}
